### ISSUE TITLE
Problems with LACP runner

### ISSUE THREAD

**Issue by feldsam** [jpirko/libteam#33]
Hello, I am using latest Fedora 26 with teamd 1.26. I experienced problems with LACP runner. Look like whle traffic go throught one port. O switch I can see in MAC table, that all mac addresses are associated with port itself and not with lag port. I post on switch manufacturer forums with details

https://community.extremenetworks.com/extreme/topics/lacp-problems

Please help me, thank you.

**Comment by sjas** [comment]
According to your link, this problem was a configuration issue on your side.

**Comment by feldsam** [comment]
Hello, yes, problem solved, there was by default fast rate = false on switch side, which causes problems.
