### ISSUE TITLE
Weighted adaptive load-balancing?

### ISSUE THREAD

**Issue by akorn** [jpirko/libteam#7]
Hi,

I have two boxes connected via several OpenVPN links (each using a different provider). They can be either Ethernet-style "tap" devices (whose speed ethtool cannot determine, but I know) or IP layer "tun" devices.

I'm looking for a way to load-balance between the links as long as they're all up, taking into account their relative capacities (e.g. using weights); and when one goes down, I'd like the load to be redistributed to the remaining links. It doesn't matter if a datagram or two is lost (transmitted over a dead link before realising it's dead).

Looking at the documentation it seems libteam can't do this (yet?); or at least it's unclear how the hash based approach could be made weighted (e.g. to send some packets of the same stream over a different link than other packets). Also, apparently the driver (or the lib) depend on being able to figure out port speeds automatically.

For some reason none of the bonding/teaming solutions I looked at seem to support anything similar, so maybe there's something fundamentally wrong with this straightforward-seeming idea? If I'm missing something, what is it? If not, is such functionality planned for libteam, or should I already be able to hack it together on my own?

Thanks!

**Comment by jpirko** [comment]
you can write your own load balancer - see teamd/teamd_balancer.c
